"""Exports the event contract to packages/schema/generated/events.schema.json.

One JSON Schema: every payload model under `$defs`, and `EventPayloads`, an object with one property per event
type pointing at its payload. The web app generates its TypeScript types from it (`npm run gen:types` in mux/web).
`tests/test_schema.py` fails when the committed file is out of date.

Run from mux/server:  .venv/bin/python -m scripts.export_schema
"""

import json
from pathlib import Path
from typing import Any

from pydantic.json_schema import models_json_schema

from mux.events.models import EVENT_PAYLOADS, EventEnvelope

OUT = Path(__file__).resolve().parents[2] / "packages" / "schema" / "generated" / "events.schema.json"


def build_schema() -> dict[str, Any]:
    models = sorted({EventEnvelope, *EVENT_PAYLOADS.values()}, key=lambda m: m.__name__)
    _, defs = models_json_schema([(m, "serialization") for m in models], ref_template="#/$defs/{model}")
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "EventPayloads",
        "description": "Generated by mux/server/scripts/export_schema.py. Do not edit by hand.",
        "type": "object",
        "properties": {type: {"$ref": f"#/$defs/{model.__name__}"} for type, model in EVENT_PAYLOADS.items()},
        "required": list(EVENT_PAYLOADS),
        "additionalProperties": False,
        "$defs": {name: _untitled_fields(d) for name, d in defs["$defs"].items()},
    }


def _untitled_fields(schema: dict[str, Any]) -> dict[str, Any]:
    """Drop the field titles pydantic adds, so the TypeScript has one interface per model and no field aliases."""
    def strip(node: Any) -> Any:
        if isinstance(node, list):
            return [strip(v) for v in node]
        if not isinstance(node, dict):
            return node
        out = {k: strip(v) for k, v in node.items() if k not in ("title", "properties")}
        if "properties" in node:  # keys here are field names, so a field called "title" stays
            out["properties"] = {name: strip(field) for name, field in node["properties"].items()}
        return out
    return {**schema, "properties": {name: strip(field) for name, field in schema.get("properties", {}).items()}}


def render() -> str:
    return json.dumps(build_schema(), indent=2, sort_keys=True) + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
