/* Generated from packages/schema/generated/events.schema.json by npm run gen:types. Do not edit. */

/**
 * Generated by mux/server/scripts/export_schema.py. Do not edit by hand.
 */
export interface EventPayloads {
  "agent.text": AgentText;
  "agent.text.delta": AgentText;
  "budget.updated": BudgetUpdated;
  "build.result": BuildResult;
  "checkpoint.created": CheckpointCreated;
  "conflict.closed": ConflictClosed;
  "conflict.evidence": ConflictEvidence;
  "conflict.opened": ConflictOpened;
  "conflict.vote": ConflictVote;
  "coordinator.reply": CoordinatorReply;
  "file.changed": FileChanged;
  "file.locked": FileLockChanged;
  "file.unlocked": FileLockChanged;
  "log.day_written": LogWritten;
  "log.task_written": LogWritten;
  "member.joined": MemberJoined;
  "member.role_changed": MemberRoleChanged;
  "message.labeled": MessageLabeled;
  "message.posted": MessagePosted;
  "plan.approved": Empty;
  "plan.drafted": PlanItems;
  "plan.edited": PlanItems;
  "plan.item_added": PlanItem;
  "plan.item_updated": PlanItemUpdated;
  "presence.join": PresenceJoined;
  "presence.leave": PresenceLeft;
  "presence.tab": PresenceTab;
  "presence.typing": PresenceTyping;
  "question.answered": QuestionAnswered;
  "question.defaulted": QuestionDefaulted;
  "question.opened": QuestionOpened;
  "room.created": RoomCreated;
  "room.paused": RoomPaused;
  "room.resumed": Empty;
  "room.rewound": RoomRewound;
  "sharing.changed": SharingChanged;
  "sitting.ended": SittingEnded;
  "task.finished": TaskRef;
  "task.started": TaskRef;
  "test.result": BuildResult;
  "tool.called": ToolCalled;
  "tool.result": ToolResult;
  "turn.interrupted": TurnInterrupted;
}
/**
 * Payload of 'agent.text' (stored, the full text of one coder turn) and 'agent.text.delta' (broadcast only).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "AgentText".
 */
export interface AgentText {
  task_id: string;
  text: string;
}
/**
 * Payload of 'budget.updated'. Field names match the web app's Budget type.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "BudgetUpdated".
 */
export interface BudgetUpdated {
  runs_cap: number;
  runs_used: number;
  tokens_cap: number;
  tokens_used: number;
}
/**
 * Payload of 'build.result' and 'test.result': at most 5 errors, and the snapshot of a passing build.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "BuildResult".
 */
export interface BuildResult {
  errors?: string[];
  passed: boolean;
  snapshot_uuid?: string | null;
  task_id: string;
}
/**
 * Payload of 'checkpoint.created'. The checkpoint's own seq is the envelope seq (R4).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "CheckpointCreated".
 */
export interface CheckpointCreated {
  checkpoint_id: string;
  manifest_id: string;
  parent_id: string | null;
  sandbox_snapshot_uuid: string | null;
  start_seq: number;
}
/**
 * Payload of 'conflict.closed'. resolved_by: "votes", "owner" or "domain" (the tie rules), or "override".
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "ConflictClosed".
 */
export interface ConflictClosed {
  conflict_id: string;
  resolved_by: string;
  result: string;
  totals: {
    [k: string]: number;
  };
}
/**
 * Payload of 'conflict.evidence': the research (None when there was none), and the vote opens until expires_at.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "ConflictEvidence".
 */
export interface ConflictEvidence {
  citations?: EvidenceCitation[];
  conflict_id: string;
  expires_at: string;
  queries?: string[];
  summary?: string | null;
}
/**
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "EvidenceCitation".
 */
export interface EvidenceCitation {
  title: string;
  url: string;
}
/**
 * Payload of 'conflict.opened'. `task_ids` are the tasks held (skipped_conflict) until the vote closes.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "ConflictOpened".
 */
export interface ConflictOpened {
  domain: "ui" | "architecture" | "scope";
  id: string;
  message_ids: string[];
  /**
   * @minItems 2
   * @maxItems 4
   */
  options: [string, string, ...string[]];
  summary: string;
  task_ids: string[];
}
/**
 * Payload of 'conflict.vote'. A later vote by the same user replaces the earlier one.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "ConflictVote".
 */
export interface ConflictVote {
  conflict_id: string;
  option: string;
  user_id: string;
  weight: number;
}
/**
 * Payload of 'coordinator.reply'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "CoordinatorReply".
 */
export interface CoordinatorReply {
  message_id?: string | null;
  text: string;
}
/**
 * Payload of 'file.changed'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "FileChanged".
 */
export interface FileChanged {
  actor: string;
  base_version: number | null;
  deleted: boolean;
  diff_summary: string;
  hash: string | null;
  path: string;
  version: number;
}
/**
 * Payload of 'file.locked' and 'file.unlocked'. `user_id` is the lock's holder.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "FileLockChanged".
 */
export interface FileLockChanged {
  path: string;
  user_id: string;
}
/**
 * Payload of 'log.task_written' and 'log.day_written'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "LogWritten".
 */
export interface LogWritten {
  checkpoint_id: string;
  log_id: string;
}
/**
 * Payload of 'member.joined'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "MemberJoined".
 */
export interface MemberJoined {
  domain_role: ("pm" | "design" | "eng") | null;
  permission: "editor" | "viewer";
  user_id: string;
}
/**
 * Payload of 'member.role_changed'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "MemberRoleChanged".
 */
export interface MemberRoleChanged {
  permission: "editor" | "viewer";
  user_id: string;
}
/**
 * Payload of 'message.labeled': what the coordinator decided for one message to the agent.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "MessageLabeled".
 */
export interface MessageLabeled {
  domain?: ("ui" | "architecture" | "scope") | null;
  fallback?: boolean;
  label: "merge" | "queue" | "interrupt" | "conflict" | "chat" | "plan";
  message_id: string;
  rationale: string;
  task_id?: string | null;
}
/**
 * Payload of 'message.posted'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "MessagePosted".
 */
export interface MessagePosted {
  id: string;
  text: string;
  to: "agent" | "team";
  user_id: string;
}
/**
 * Payload of 'plan.approved' and 'room.resumed'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "Empty".
 */
export interface Empty {}
/**
 * Payload of 'plan.drafted' and 'plan.edited': the whole plan, in order.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PlanItems".
 */
export interface PlanItems {
  items: PlanItem[];
}
/**
 * One task of the plan. Also the payload of 'plan.item_added'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PlanItem".
 */
export interface PlanItem {
  id: string;
  merged_notes?: string[];
  notes?: string | null;
  owner_role?: ("pm" | "design" | "eng") | null;
  status?: "draft" | "todo" | "doing" | "done" | "skipped_conflict" | "skipped_question" | "blocked";
  title: string;
}
/**
 * Payload of 'plan.item_updated'. `changes` holds only the fields that change.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PlanItemUpdated".
 */
export interface PlanItemUpdated {
  changes: {
    [k: string]: unknown;
  };
  id: string;
}
/**
 * Payload of 'presence.join' (broadcast, never stored).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PresenceJoined".
 */
export interface PresenceJoined {
  name: string | null;
  tab: ("feed" | "preview" | "code" | "cards") | null;
  typing: boolean;
  user_id: string;
}
/**
 * Payload of 'presence.leave' (broadcast, never stored).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PresenceLeft".
 */
export interface PresenceLeft {
  user_id: string;
}
/**
 * Payload of 'presence.tab' (broadcast, never stored).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PresenceTab".
 */
export interface PresenceTab {
  tab: "feed" | "preview" | "code" | "cards";
  user_id: string;
}
/**
 * Payload of 'presence.typing' (broadcast, never stored).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "PresenceTyping".
 */
export interface PresenceTyping {
  typing: boolean;
  user_id: string;
}
/**
 * Payload of 'question.answered'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "QuestionAnswered".
 */
export interface QuestionAnswered {
  answer: string;
  question_id: string;
  user_id: string;
}
/**
 * Payload of 'question.defaulted': nobody answered in time, so the default is the answer.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "QuestionDefaulted".
 */
export interface QuestionDefaulted {
  answer: string;
  question_id: string;
}
/**
 * Payload of 'question.opened': the coder asks the room. Its task is skipped_question until an answer.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "QuestionOpened".
 */
export interface QuestionOpened {
  default: string;
  expires_at: string;
  id: string;
  /**
   * @minItems 2
   */
  options: [string, string, ...string[]];
  task_id: string | null;
  text: string;
}
/**
 * Payload of 'room.created'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "RoomCreated".
 */
export interface RoomCreated {
  description: string;
  owner_id: string;
  title: string;
}
/**
 * Payload of 'room.paused': which cap was reached. 'room.resumed' has an empty payload.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "RoomPaused".
 */
export interface RoomPaused {
  reason: "tokens" | "runs";
}
/**
 * Payload of 'room.rewound' (R2): the new version of every path whose content changed, applied as given.
 * Paths missing from the target checkpoint's manifest are removed; they keep their high-water marks.
 * `plan` is the checkpoint's plan, which becomes the room's plan (rewinds stored before it was added lack it).
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "RoomRewound".
 */
export interface RoomRewound {
  checkpoint_id: string;
  plan?: PlanItem[];
  versions: {
    [k: string]: number;
  };
}
/**
 * Payload of 'sharing.changed'. link_permission is None when link_access is 'restricted'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "SharingChanged".
 */
export interface SharingChanged {
  link_access: "restricted" | "anyone";
  link_permission: ("editor" | "viewer") | null;
}
/**
 * Payload of 'sitting.ended': nobody connected for 30 minutes, or the owner ended the session.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "SittingEnded".
 */
export interface SittingEnded {
  reason: "idle" | "owner";
}
/**
 * Payload of 'task.started' and 'task.finished'.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "TaskRef".
 */
export interface TaskRef {
  task_id: string;
}
/**
 * Payload of 'tool.called'. Long string arguments (file contents) are cut short.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "ToolCalled".
 */
export interface ToolCalled {
  arguments: {
    [k: string]: unknown;
  };
  name: string;
  task_id: string;
}
/**
 * Payload of 'tool.result': whether the call worked, and a one-line summary.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "ToolResult".
 */
export interface ToolResult {
  name: string;
  ok: boolean;
  summary: string;
  task_id: string;
}
/**
 * Payload of 'turn.interrupted': the coder stopped at a turn boundary and starts the task again.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "TurnInterrupted".
 */
export interface TurnInterrupted {
  reason: string;
  task_id: string;
}
/**
 * Wire/storage shape of every event.
 *
 * This interface was referenced by `EventPayloads`'s JSON-Schema
 * via the `definition` "EventEnvelope".
 */
export interface EventEnvelope {
  actor: string;
  payload: {
    [k: string]: unknown;
  };
  room_id: string;
  seq: number;
  ts: string;
  type: string;
}
