/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // GitHub Dark room tokens (stitch: mux_collaborative_ide_workspace)
        bg: '#010409',
        panel: '#0d1117',
        raised: '#161b22',
        line: '#30363d',
        ink: '#e6edf3',
        muted: '#8d96a0',
        faint: '#6e7681',
        'on-accent': '#ffffff',
        'code-bg': '#010409',
        coord: '#3b82f6',
        coder: '#06b6d4',
        ok: '#3b82f6',
        conflict: '#f85149',
        ask: '#a371f7',
        queue: '#06b6d4',

        // Developer Workspace System tokens (stitch: overview / rooms / pricing)
        surface: '#0d1117',
        'surface-dim': '#0d1117',
        'surface-bright': '#353940',
        'surface-container-lowest': '#0a0e14',
        'surface-container-low': '#11161d',
        'surface-container': '#161b22',
        'surface-container-high': '#21262d',
        'surface-container-highest': '#30363d',
        'on-surface': '#dfe2eb',
        'on-surface-variant': '#8b949e',
        outline: '#8b949e',
        'outline-variant': '#3d444d',
        primary: '#3b82f6',
        'on-primary': '#ffffff',
        'primary-container': '#3b82f6',
        'on-primary-container': '#ffffff',
        'primary-fixed': '#93c5fd',
        secondary: '#06b6d4',
        'on-secondary': '#ffffff',
        'secondary-container': '#1d4ed8',
        'on-secondary-container': '#e6ecff',
        tertiary: '#06b6d4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#06b6d4',
        'on-tertiary-container': '#002026',
        error: '#ffb4ab',
        'error-strong': '#f85149',
      },
      fontFamily: {
        display: ['var(--nf-mona)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        body: ['var(--nf-mona)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['var(--nf-plex)', 'ui-monospace', 'Menlo', 'Consolas', 'monospace'],
        ui: ['var(--nf-inter)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        headline: ['var(--nf-jetbrains)', 'ui-monospace', 'Menlo', 'monospace'],
        code: ['var(--nf-jetbrains)', 'ui-monospace', 'Menlo', 'monospace'],
      },
      fontSize: {
        'code-sm': ['11px', { lineHeight: '16px' }],
        'code-md': ['13px', { lineHeight: '20px' }],
        'body-sm': ['12px', { lineHeight: '16px' }],
        'body-md': ['13px', { lineHeight: '20px' }],
        'body-lg': ['15px', { lineHeight: '24px' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        gutter: '1rem',
      },
      animation: {
        'blink': 'blink 1s steps(1) infinite',
        'spin': 'spin 1.1s linear infinite',
        'ping': 'ping 2s ease-in-out infinite',
        'fade-up': 'fade-up .6s ease-out both',
      },
      keyframes: {
        blink: {
          '50%': { opacity: '0' },
        },
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'none' },
        },
      },
    },
  },
  plugins: [],
}
